[telegram]
# Получите токен у @BotFather в Telegram
bot_token = "8300140302:AAFLOrUk1388aPvVhcfzs8pO8snDyiQVEC4"

# ID вашего канала, куда будут приходить уведомления (например, -100123456789)
# Бот должен быть администратором в этом канале
channel_id = "-1002971840298"

[parser]
# Пауза в секундах между полными циклами проверки всех ссылок
pause_general = 5

# Пауза в секундах между проверкой каждой отдельной ссылки
pause_between_links = 1